version: '3.8'

services:
    redis:
        image: redis:7
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - coinnetwork

    coinpilot:
        build:
            context: ./docker
        container_name: coinpilot
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        tty: true
        user: "1000:1000"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "8081:8000"
        depends_on:
            - redis
        command: >
            sh -c "/var/www/html/docker/entrypoint.sh && php artisan serve --host=0.0.0.0 --port=8000"
        networks:
            - coinnetwork
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
            interval: 10s
            timeout: 5s
            retries: 3

    worker1:
        build:
            context: ./docker
        container_name: worker1
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            redis:
                condition: service_started
            coinpilot:
                condition: service_healthy
        command: php artisan queue:work redis --queue=transfer --timeout=0
        networks:
            - coinnetwork

    worker2:
        build:
            context: ./docker
        container_name: worker2
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            redis:
                condition: service_started
            coinpilot:
                condition: service_healthy
        command: php artisan queue:work redis --queue=transfer --timeout=0
        networks:
            - coinnetwork
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 3

networks:
  coinnetwork:
    driver: bridge